#!/bin/bash

NUMBER=1
STATE='+'

generatorPID=$(head -n 1 "pipe")

(tail -f pipe) |
while true; do
	read LINE
	case "$LINE" in
		"QUIT")
			echo "end with QUIT"
			break
			;;
		'+')
			STATE='+'
			;;
		'-')
			STATE='-'
			;;
		'*')
			STATE='*'
			;;
		'/')
			STATE='/'
			;;
		'0')
			if [[ "$STATE" == '/' ]];then 
				echo "cannot divide by zero!"
				echo "enter another number:"
			fi
			;;
		[0-9]*)
			NUMBER=$(echo "scale=5; ${NUMBER} $STATE ${LINE}" | bc)
			echo $NUMBER
			;;
		*)
			echo "end because of invalid input"
			break
			;;		
	esac
done

kill $generatorPID
exit
