#! /bin/bash

echo "----------"
echo "MENU:"
echo "1 -> nano"
echo "2 -> vi"
echo "3 -> links"
echo "4 -> exit"
echo "----------"

read item

while [[ $item != "4" ]]  
do
case $item in
1 )
	nano
    	;;
2 )
	vi
	;;
3 )
	links
	;;
esac
read item
done