#!/bin/bash 

sourceDirectory="$HOME/source"
backupDirectory="$HOME/Backup"
backupReportDirectory="$HOME/backup-report"
if [ ! -f "$backupReportDirectory" ]; then 
	touch $backupReportDirectory
fi 

today=$(date '+%F')
lastDate=$(
	echo $(ls $HOME | 
		grep -E "^Backup" | 
		sort | 
		tail -n 1
	) | 
	awk -F- '{printf("%s-%s-%s", $2, $3, $4)}')

if [[ "$(date -d "-7days" '+%F')" > "$lastDate" ]]; then
	currDirectory=$backupDirectory-$today
	mkdir $currDirectory
	echo "Create Backup-$today" >> $backupReportDirectory
else 
	currDirectory=$backupDirectory-$lastDate
	echo "Change Backup-$lastDate" >> $backupReportDirectory
fi

for idx in $(ls $sourceDirectory); do
	currFile="$currDirectory/$idx"
	source="$sourceDirectory/$idx"
	if [[ (-f "$currFile") && (! -z "$(diff $source $currFile)") ]]; then
		cp "$currFile" "$currFile.$today"
		cp "$source" "$currFile"
		echo "add new $currFile" >> $backupReportDirectory
	else
		cp "$source" "$currFile"
		echo "add $currFile" >> $backupReportDirectory
	fi
done
