#!/usr/bin/env bash

: > logs/2step/ram.log
: > logs/2step/swap.log
: > logs/2step/params1.log
: > logs/2step/params2.log
: > logs/2step/top5.log

while true
do
    BOTH=$(free | tail -n2 | awk '{print $4;}')
    echo "$BOTH" | head -n1 >> logs/2step/ram.log
    echo "$BOTH" | tail -n1 >> logs/2step/swap.log

    top -b -n1 | grep -m 1 "mem.bash" >> logs/2step/params1.log
    top -b -n1 | grep -m 1 "mem2.bash" >> logs/2step/params2.log

    top -b -n1 -o %MEM | head -n12 | tail -n5 >> logs/2step/top5.log
    echo "" >> logs/2step/top5.log

    sleep 0.1s
done
