#!/bin/bash
		
cd /proc
output="$HOME/lab2/iv.out"

for pid in $(ps -Ao pid | grep -oh -E [0-9]+); do
	if [[ -e "$pid" ]]; then
		echo -n "ProcessID = $pid : Parent_ProcessID = $(awk '$1=="PPid:" { print $2 }' $pid/status) : "
	    	echo "Avarage_Running_Time = $(awk -F '([[:blank:]]*):([[:blank:]]*)' '
	    	BEGIN {
	    		nr_switches=0; 
	    		sum_exec_runtime=0
	    	} {
	    		if ($1 == "nr_switches") {
	    			nr_switches=$2
	    		}
	   	 	if ($1 == "se.sum_exec_runtime") {
	   	 		sum_exec_runtime=$2
	   	 	}
	    	} END {
	    		if (nr_switches!=0) {
	    			print sum_exec_runtime/nr_switches
	    		}
	    	}' $pid/sched)."
	fi
done | sort -n -k 7 > $output
